apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2021-12-01T14:19:20Z'
  generation: 25
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2021-12-01T16:06:36Z'
  name: new-pipeline
  namespace: dmn-simple
  resourceVersion: '1496834'
  selfLink: /apis/tekton.dev/v1beta1/namespaces/dmn-simple/pipelines/new-pipeline
  uid: b920e58a-1307-4263-af7e-67fef3ab26e7
spec:
  params:
    - default: simple-dmn-rule
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
      description: The application git repository url
      name: SOURCE_GIT_URL
      type: string
    - default: kogito-dmn-simple-rule
      description: The subdirectory in the git repository
      name: SOURCE_GIT_CONTEXT_DIR
      type: string
    - default: main
      description: The application git repository revision
      name: SOURCE_GIT_REVISION
      type: string
    - default: >-
        http://maven-mirror-openshift-operators.apps.cluster-hlfs7.hlfs7.sandbox85.opentlc.com/repository/maven-public/
      description: Maven mirror for Maven Builds
      name: MAVEN_MIRROR_URL
      type: string
    - default: dmn-simple
      description: Namespace where the buildconfig is located
      name: NAMESPACE_DEV
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.SOURCE_GIT_URL)
        - name: revision
          value: $(params.SOURCE_GIT_REVISION)
        - name: deleteExisting
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:afc5d3f9efe26c7042635d43b8ffd09d67936e3d0b6b901dc08a33e20313d361
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: generate-tag
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: generate-tag
    - name: maven-build
      params:
        - name: MAVEN_IMAGE
          value: 'registry.access.redhat.com/ubi8/openjdk-11:1.3'
        - name: CONTEXT_DIR
          value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - compile
            - package
        - name: MAVEN_MIRROR_URL
          value: $(params.MAVEN_MIRROR_URL)
      runAfter:
        - generate-tag
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      params:
        - name: FROM_FILE
          value: >-
            ./source/$(params.SOURCE_GIT_CONTEXT_DIR)/target/$(params.APP_NAME)-1.0-SNAPSHOT-runner.jar
        - name: NAMESPACE
          value: $(params.NAMESPACE_DEV)
        - name: BUILDCONFIG
          value: $(params.APP_NAME)
      runAfter:
        - maven-build
      taskRef:
        kind: Task
        name: s2i-binary
      workspaces:
        - name: source
          workspace: app-source
    - name: tag-image-for-development
      params:
        - name: ARGS
          value:
            - tag
            - '$(params.NAMESPACE_DEV)/$(params.APP_NAME):latest'
            - >-
              $(params.NAMESPACE_DEV)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: app-source
    - name: maven-settings
