apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"simple-dmn-rule:latest","namespace":"dmn-simple"},"fieldPath":"spec.template.spec.containers[?(@.name==\"simple-dmn-rule\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: simple-dmn-rule
    app.kubernetes.io/component: simple-dmn-rule
    app.kubernetes.io/instance: simple-dmn-rule
  name: simple-dmn-rule
  namespace: dmn-simple
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: simple-dmn-rule
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: simple-dmn-rule
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/dmn-simple/simple-dmn-rule@sha256:1d44a53e233ce4a76c307079646435494aac6c52324af7f3de7b600887161f7f
        imagePullPolicy: IfNotPresent
        name: simple-dmn-rule
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
