apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2021-11-12T11:40:19Z"
  labels:
    app: kogito-dmn-simple
    app.kubernetes.io/component: kogito-dmn-simple
    app.kubernetes.io/instance: kogito-dmn-simple
  name: kogito-dmn-simple
  namespace: pbrown-dev
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: kogito-dmn-simple:latest
    generation: 3
    name: latest
    referencePolicy:
      type: Source
