
  
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: dmn-simple-rule
spec:
  buildImage: quay.io/kiegroup/kogito-builder:latest
  runtimeImage: quay.io/kiegroup/kogito-runtime-jvm:latest
  type: LocalSource
 
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: dmn-simple-rule
spec:
  infra:
    - KAFKA_INFRA_NAME