apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2021-12-07T14:59:16Z'
  generation: 202
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:destination':
            .: {}
            'f:namespace': {}
            'f:server': {}
          'f:project': {}
          'f:source':
            .: {}
            'f:path': {}
            'f:repoURL': {}
            'f:targetRevision': {}
      manager: Mozilla
      operation: Update
      time: '2021-12-07T14:59:16Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:syncPolicy':
            .: {}
            'f:automated': {}
      manager: argocd-server
      operation: Update
      time: '2021-12-07T16:28:44Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:history': {}
          'f:sourceType': {}
          .: {}
          'f:sync':
            .: {}
            'f:comparedTo':
              .: {}
              'f:destination':
                .: {}
                'f:namespace': {}
                'f:server': {}
              'f:source':
                .: {}
                'f:path': {}
                'f:repoURL': {}
                'f:targetRevision': {}
            'f:revision': {}
            'f:status': {}
          'f:health':
            .: {}
            'f:status': {}
          'f:resources': {}
          'f:summary':
            .: {}
            'f:images': {}
          'f:reconciledAt': {}
          'f:operationState':
            .: {}
            'f:finishedAt': {}
            'f:message': {}
            'f:operation':
              .: {}
              'f:initiatedBy':
                .: {}
                'f:username': {}
              'f:retry': {}
              'f:sync':
                .: {}
                'f:revision': {}
                'f:syncStrategy':
                  .: {}
                  'f:hook': {}
            'f:phase': {}
            'f:startedAt': {}
            'f:syncResult':
              .: {}
              'f:resources': {}
              'f:revision': {}
              'f:source':
                .: {}
                'f:path': {}
                'f:repoURL': {}
                'f:targetRevision': {}
      manager: argocd-application-controller
      operation: Update
      time: '2021-12-07T16:28:45Z'
  name: simple-dmn-rule
  namespace: dmn-simple
  resourceVersion: '2622607'
  selfLink: >-
    /apis/argoproj.io/v1alpha1/namespaces/dmn-simple/applications/simple-dmn-rule
  uid: 63b56eaa-adc2-48ed-8997-dab46c0a2b33
spec:
  destination:
    namespace: dmn-simple
    server: 'https://kubernetes.default.svc'
  project: simple-dmn-rule
  source:
    path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
    repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
status:
  health:
    status: Progressing
  history:
    - deployStartedAt: '2021-12-07T16:11:12Z'
      deployedAt: '2021-12-07T16:11:15Z'
      id: 0
      revision: 822c315e8e548d7b60431e4cac99b45f58713845
      source:
        path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
        repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
        targetRevision: HEAD
    - deployStartedAt: '2021-12-07T16:28:19Z'
      deployedAt: '2021-12-07T16:28:21Z'
      id: 1
      revision: b3c7d7d078079779803b6ed4ac7a914cf276843a
      source:
        path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
        repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
        targetRevision: HEAD
    - deployStartedAt: '2021-12-07T16:28:44Z'
      deployedAt: '2021-12-07T16:28:45Z'
      id: 2
      revision: b3c7d7d078079779803b6ed4ac7a914cf276843a
      source:
        path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
        repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
        targetRevision: HEAD
  operationState:
    finishedAt: '2021-12-07T16:28:45Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: b3c7d7d078079779803b6ed4ac7a914cf276843a
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2021-12-07T16:28:44Z'
    syncResult:
      resources:
        - syncPhase: Sync
          message: service/simple-dmn-rule unchanged
          name: simple-dmn-rule
          status: Synced
          kind: Service
          version: v1
          hookPhase: Running
          namespace: dmn-simple
          group: ''
        - syncPhase: Sync
          message: deployment.apps/simple-dmn-rule created
          name: simple-dmn-rule
          status: Synced
          kind: Deployment
          version: v1
          hookPhase: Running
          namespace: dmn-simple
          group: apps
        - syncPhase: Sync
          message: route.route.openshift.io/simple-dmn-rule unchanged
          name: simple-dmn-rule
          status: Synced
          kind: Route
          version: v1
          hookPhase: Running
          namespace: dmn-simple
          group: route.openshift.io
        - syncPhase: Sync
          message: buildconfig.build.openshift.io/simple-dmn-rule unchanged
          name: simple-dmn-rule
          status: Synced
          kind: BuildConfig
          version: v1
          hookPhase: Running
          namespace: dmn-simple
          group: build.openshift.io
        - syncPhase: Sync
          message: imagestream.image.openshift.io/simple-dmn-rule configured
          name: simple-dmn-rule
          status: Synced
          kind: ImageStream
          version: v1
          hookPhase: Running
          namespace: dmn-simple
          group: image.openshift.io
      revision: b3c7d7d078079779803b6ed4ac7a914cf276843a
      source:
        path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
        repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
        targetRevision: HEAD
  reconciledAt: '2021-12-08T14:36:20Z'
  resources:
    - health:
        status: Healthy
      kind: Service
      name: simple-dmn-rule
      namespace: dmn-simple
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          Waiting for rollout to finish: 0 of 1 updated replicas are
          available...
        status: Progressing
      kind: Deployment
      name: simple-dmn-rule
      namespace: dmn-simple
      status: OutOfSync
      version: v1
    - group: build.openshift.io
      kind: BuildConfig
      name: simple-dmn-rule
      namespace: dmn-simple
      status: Unknown
      version: v1
    - group: image.openshift.io
      kind: ImageStream
      name: simple-dmn-rule
      namespace: dmn-simple
      status: Unknown
      version: v1
    - group: route.openshift.io
      kind: Route
      name: simple-dmn-rule
      namespace: dmn-simple
      status: Unknown
      version: v1
  sourceType: Kustomize
  summary:
    images:
      - 'dmn-simple/simple-dmn-rule:dev-2021-12-08-13-59-27'
  sync:
    comparedTo:
      destination:
        namespace: dmn-simple
        server: 'https://kubernetes.default.svc'
      source:
        path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
        repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
        targetRevision: HEAD
    revision: b3c7d7d078079779803b6ed4ac7a914cf276843a
    status: OutOfSync
