apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  generation: 202
  name: simple-dmn-rule
  namespace: dmn-simple
  resourceVersion: '2622607'
  selfLink: >-
    /apis/argoproj.io/v1alpha1/namespaces/dmn-simple/applications/simple-dmn-rule
  uid: 63b56eaa-adc2-48ed-8997-dab46c0a2b33
spec:
  destination:
    namespace: dmn-simple
    server: 'https://kubernetes.default.svc'
  project: simple-dmn-rule
  source:
    path: kogito-dmn-simple-kustomize/kogito-dmn-simple/overlays/development
    repoURL: 'https://github.com/pauljamesbrown/rhdm-pipeline-example.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}

  