apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2021-10-11T13:56:24Z'
  generation: 3
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:results': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2021-10-11T15:16:26Z'
  name: build-and-deploy-rule-application
  namespace: 888c4-pipeline
  resourceVersion: '1204969282'
  selfLink: >-
    /apis/tekton.dev/v1beta1/namespaces/888c4-pipeline/pipelines/build-and-deploy-rule-application
  uid: bc617da2-2d5a-42e3-9083-10ef0badea9f
spec:
  params:
    - default: 888c4
      description: OCP_USER PREFIX
      name: OCP_USER
      type: string
    - default: self-healing-simple-rule
      description: The application deployment name
      name: APP_NAME
      type: string
    - default: 'https://github.com/pauljamesbrown/rhdm-pipeline-example'
      description: The application git repository url
      name: SOURCE_GIT_URL
      type: string
    - default: master
      description: The application git repository revision
      name: SOURCE_GIT_REVISION
      type: string
    - default: self-healing-simple-rule
      description: The subdirectory in the git repository
      name: SOURCE_GIT_CONTEXT_DIR
      type: string
    - default: 'http://homework-nexus.gpte-hw-cicd.svc:8081/repository/maven-all-public/'
      description: Maven mirror for Maven Builds
      name: MAVEN_MIRROR_URL
      type: string
    - default: homework-nexus-registry.apps.shared-dev4.dev4.openshift.opentlc.com
      description: External URL for the container registry to set the production image from
      name: NEXUS_REGISTRY_URL
      type: string
    - default: 888c4-dev-rhdm-simple-rule
      description: Namespace where the buildconfig is located
      name: NAMESPACE_DEV
      type: string
    - default: 'false'
      description: OCP_USER of the student
      name: DEPLOY_SERVERLESS
      type: string
  results:
    - description: The Production Image Tag
      name: image-tag
      value: prod-$(tasks.generate-tag.results.image-tag)
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.SOURCE_GIT_URL)
        - name: revision
          value: $(params.SOURCE_GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: app-source
    - name: generate-tag
      taskRef:
        kind: Task
        name: generate-tag
    - name: maven-build
      params:
        - name: MAVEN_IMAGE
          value: 'registry.access.redhat.com/ubi8/openjdk-11:1.3'
        - name: CONTEXT_DIR
          value: ./$(params.SOURCE_GIT_CONTEXT_DIR)
        - name: GOALS
          value:
            - '-DskipTests'
            - clean
            - compile
            - package
        - name: MAVEN_MIRROR_URL
          value: $(params.MAVEN_MIRROR_URL)
      runAfter:
        - git-clone
        - generate-tag
      taskRef:
        kind: Task
        name: maven
      workspaces:
        - name: source
          workspace: app-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      params:
        - name: FROM_FILE
          value: >-
            ./source/$(params.SOURCE_GIT_CONTEXT_DIR)/target/$(params.APP_NAME)-1.0-SNAPSHOT-runner.jar
        - name: NAMESPACE
          value: $(params.NAMESPACE_DEV)
        - name: BUILDCONFIG
          value: $(params.APP_NAME)
      runAfter:
        - maven-build
      taskRef:
        kind: Task
        name: s2i-binary
      workspaces:
        - name: source
          workspace: app-source
    - name: tag-image-for-development
      params:
        - name: ARGS
          value:
            - tag
            - '$(params.NAMESPACE_DEV)/$(params.APP_NAME):latest'
            - >-
              $(params.NAMESPACE_DEV)/$(params.APP_NAME):dev-$(tasks.generate-tag.results.image-tag)
      runAfter:
        - build-image
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: app-source
    - name: maven-settings
    - name: images-url
