apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-dmn-rule
spec:
  template:
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/dmn-simple/simple-dmn-rule@sha256:1d44a53e233ce4a76c307079646435494aac6c52324af7f3de7b600887161f7f
        name: simple-dmn-rule