apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
    openshift.io/image.dockerRepositoryCheck: "2021-12-06T16:24:40Z"
  labels:
    build: simple-dmn-rule
  name: simple-dmn-rule
  namespace: dmn-simple
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: ImageStreamImage
      name: simple-dmn-rule@sha256:6956548d61dc9e5cde7865bbff76ff3da059c3f09d8864a50c409f243f572c3b
      namespace: dmn-simple
    generation: 4
    name: dev-2021-12-06-16-28-38
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: ImageStreamImage
      name: simple-dmn-rule@sha256:1d44a53e233ce4a76c307079646435494aac6c52324af7f3de7b600887161f7f
      namespace: dmn-simple
    generation: 5
    name: dev-2021-12-07-11-29-31
    referencePolicy:
      type: Source
  - annotations: null
    from:
      kind: DockerImage
      name: simple-dmn-rule:latest
    generation: 3
    name: latest
    referencePolicy:
      type: Source
