apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- ./image-stream.yaml
- ./build-config.yaml

namespace: dmn-simple

patches:
  - ./deployment-patches.yaml